Adding reference to mdformat-frontmatter as an available plugin
executablebooks/mdformat pull request #142
Opened 2021-03-09 04:04 UTC by butler54

I recently created a plugin to allow mdformat to handle yaml headers used by some tools. This PR is to add that plugin to the documentation of mdformat.

Signed-off-by: Chris Butler <chris@thebutlers.me>

2021-03-09 12:28 UTC, hukkinj1 requested changes
Hey there!

I had a look at the plugin, looking good!

I'd like to suggest making the plugin not error given invalid YAML. Reasoning: I think generally pretty much any string should be valid Markdown, interpretation just changes depending on content. A formatter should generally not error on content that is valid Markdown, it should simply apply its formatting rules. Also the [front matter parser plugin](https://www.npmjs.com/package/markdown-it-front-matter) docs explicitly state that "YAML is not required".

Instead I suggest just passing through the non-YAML front matter text and logging a warning:
```python
import mdformat.renderer
mdformat.renderer.LOGGER.warning("Invalid YAML in a front matter block")
```
This log will printed to stderr if using the CLI.

2021-03-09 12:28 UTC, hukkinj1 commented on README.md
> +    <td>Adds the capability parse yaml headers to markdown documents.</td>
Suggestion:
```suggestion
    <td>Adds support for front matter, and formats YAML front matter</td>
```

2021-03-15 01:45 UTC, butler54 commented
> Hey there!
> 
> I had a look at the plugin, looking good!
> 
> I'd like to suggest making the plugin not error given invalid YAML. Reasoning: I think generally pretty much any string should be valid Markdown, interpretation just changes depending on content. A formatter should generally not error on content that is valid Markdown, it should simply apply its formatting rules. Also the [front matter parser plugin](https://www.npmjs.com/package/markdown-it-front-matter) docs explicitly state that "YAML is not required".
> 
> Instead I suggest just passing through the non-YAML front matter text and logging a warning:
> 
> ```python
> import mdformat.renderer
> mdformat.renderer.LOGGER.warning("Invalid YAML in a front matter block")
> ```
> 
> This log will printed to stderr if using the CLI.

Hey there, 
Sorry for missing the comment. I'll have a look and update you when it's done with respect to the plugin.

2021-03-15 02:16 UTC, butler54 commented
I updated the plugin based on your recommendations. It should be okay now.

2021-03-15 02:57 UTC, merged