[ENH] Add Configurable Line Endings
executablebooks/mdformat pull request #226
Opened 2021-06-18 03:15 UTC by DragonCrafted87

Fix for Issue #224 

Add new Parameter
--line-ending

that controls how the line endings are set for the output file

2021-06-18 10:29 UTC, hukkin requested changes
Thank you _very __very__ much_ for doing the research and coming up with an excellent fix. Much appreciated.

I've requested some changes to reduce the amount of configuration as I don't want to add any API surface unless a real world user with the need for it appears.

In addition to these changes we need to fix this line: https://github.com/executablebooks/mdformat/blob/ee13da698bcb24c1af05bf243b341845e4b60bdc/mdformat/_api.py#L62

We need to change it to 
```python
atomic_write(f, formatted_md, options.get("end_of_line", "lf"))
```

Also we need a simple test that ensures no `crlf`s are written to files by default. Running that in CI on Windows will validate our changes and prevent regressions. I can also add this test myself if you're not familiar with the test setup.

2021-06-18 10:29 UTC, hukkin commented on mdformat/_util.py
> +def atomic_write(path: Path, text: str, line_ending: Optional[str] = None) -> None:
```suggestion
def atomic_write(path: Path, text: str, line_ending: str) -> None:
```

2021-06-18 10:29 UTC, hukkin commented on mdformat/_util.py
>      fd, tmp_path = tempfile.mkstemp(dir=path.parent)
```suggestion
    newline = "\r\n" if line_ending == "crlf" else "\n"
    fd, tmp_path = tempfile.mkstemp(dir=path.parent)
```

2021-06-18 10:29 UTC, hukkin commented on mdformat/_util.py
> +        with open(fd, "w", encoding="utf-8", newline=line_ending) as f:
```suggestion
        with open(fd, "w", encoding="utf-8", newline=newline) as f:
```

2021-06-18 10:29 UTC, hukkin commented on mdformat/_cli.py
> +
```suggestion
```

2021-06-18 10:29 UTC, hukkin commented on mdformat/_cli.py
> +    )
```suggestion
    parser.add_argument(
        "--end-of-line",
        default="lf",
        choices=("lf", "crlf"),
        help="output file line ending mode",
    )
```

2021-06-18 10:29 UTC, hukkin commented on mdformat/_cli.py
> +                atomic_write(path, formatted_str, options.get("line_ending", None))
```suggestion
                atomic_write(path, formatted_str, options["end_of_line"])
```

2021-06-18 10:58 UTC, hukkin commented
I'm actually a bit tempted to not add the configuration option at all, and just always use a `\n` character always. This is what I thought the current behavior was until you proved otherwise :smile: 

I'm not sure if there's a good reason to prefer `\r\n` and if there's one person on earth who needs that, running in serial with an end of line fixer should solve that.

If it's later apparent that many people need `\r\n` then the configuration could be introduced.

What do you think @DragonCrafted87 ?

2021-06-18 14:37 UTC, DragonCrafted87 commented
yeah as while hardcoding it to purely `lf` would work in my case and I imagine most others I'm sure there's someone who wants all `crlf` line endings and like you said it will fail if there is an end of line fixer running in line with it in the same way I noticed it. 
I should be able to clean up the rest of the comments this evening though I may need a hand with the test as I tend to use python more for scripting than anything complicated enough to need a test suite

2021-06-18 22:46 UTC, hukkin commented
:+1: 

For tests, please add these to `tests/test_cli.py`:
```python
def test_eol__lf(tmp_path):
    file_path = tmp_path / "test.md"
    file_path.write_bytes(b"Oi\r\n")
    assert run([str(file_path), "--end-of-line=lf"]) == 0
    assert file_path.read_bytes() == b"Oi\n"


def test_eol__crlf(tmp_path):
    file_path = tmp_path / "test.md"
    file_path.write_bytes(b"Oi\n")
    assert run([str(file_path), "--end-of-line=crlf"]) == 0
    assert file_path.read_bytes() == b"Oi\r\n"
```

and these to `tests/test_api.py`:
```python
def test_eol__lf(tmp_path):
    file_path = tmp_path / "test.md"
    file_path.write_bytes(b"Oi\r\n")
    mdformat.file(str(file_path), options={"end_of_line": "lf"})
    assert file_path.read_bytes() == b"Oi\n"


def test_eol__crlf(tmp_path):
    file_path = tmp_path / "test.md"
    file_path.write_bytes(b"Oi\n")
    mdformat.file(str(file_path), options={"end_of_line": "crlf"})
    assert file_path.read_bytes() == b"Oi\r\n"
```

2021-06-19 02:04 UTC, DragonCrafted87 commented
that push should have everything accounted for to just do the `crlf` and `lf` options. Thank you for the tests if I ever wind up doing a larger project in python I'll have to take a closer look at pytest as it looks like its nice and straight forward for a test system

2021-06-19 07:39 UTC, merged

2021-06-19 07:40 UTC, hukkin commented
Thanks this is great! I'll try to have this released later today.