✨ Allow env dict to be passed to renderer
executablebooks/mdformat pull request #35
Opened 2020-09-25 23:04 UTC by chrisjsewell

This provides a hook for passing variables to the parsing/render process,
which in-turn provides a simple way of allowing plugins to accept variable arguments from the API or CLI.

Note this is back-incompatible for parser plugins, since `update_mdit` now also gets passed this env dict.

2020-09-26 22:23 UTC, hukkinj1 commented
Hey, could you help me understand a few things.

We already pass some state to the parser and render in the `options` dict. Why not use that here as well? I'm having a bit of a hard time understanding the `options` and `env` distinction. I've only seen the `env` used for reference link refs, so thought that the use-case for that is parser output that for one reason or the other doesn't fit in the token stream. The definition [here](https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md):
> An env sandbox can be used alongside tokens to inject external variables for your parsers and renderers.

Makes me think that the source of `env` data is not always the parser. Then how is it different from `options`?

2020-09-26 22:27 UTC, hukkinj1 commented
Also would be interested in how you plan to use this feature exactly? Is there a use case for `update_mdit` receiving the `env` or is it enough if the render function does so, etc?

2020-09-27 00:33 UTC, chrisjsewell commented
> I'm having a bit of a hard time understanding the options and env distinction in the markdown-it world in general

The difference is that `options` should remain constant over multiple text parses, whereas `env` is transient and gets reset for each parse.
For example, you should set up your `MarkdownIt` object once then reuse it for all parsing:

```python
mdit = MarkdownIt()
# this option wil be used for every parse
mdit.option["a"] = 1
# but the env will only be used for the parse it is set on
mdit.parse("hallo", env={"b": 1})
mdit.parse("hallo")
```

So yeh you are probably right that this data should update options.

Note, mdformat anyhow diminishes this distinction a bit, because a new `MarkdownIt` instance is created for every parse.
I guess technically, in `mdformat._cli.run`, you should set up a single `MarkdownIt` instance and use it to parse all files, rather than calling `mdformat.text` and creating a new one every time.
(this is more important in long running/responsive programs, for example VS Code sets up a single `MarkdownIt` instance in memory, and will use it for every call to update a preview)

> Also would be interested in how you plan to use this feature exactly?

Any way I want lol.
If a plugin wants to be a bit more "unopinionated" (i.e. accepting configuration) then this should be allowed.
For an example though, `markdown_it.extensions.texmath.texmath_plugin` can be initialized with different styles of delimiter: `dollars`, `brackets`, `gitlab`, etc.
I don't want to have to create a separate plugin for every style, over just calling something like  `mdformat -e texmath-delim=brackets`

2020-09-27 00:58 UTC, chrisjsewell commented
In 0672535 I've moved to setting options rather than env

2020-09-27 02:16 UTC, hukkinj1 commented
Thanks for the explanation!

> ...how you plan to use this feature exactly?
> > Any way I want lol...

Aha, if it's as general purpose as this, then what do you think about the following: we give plugins the possibility to add `argparse` arguments of their own. Then in the render phase we'd pass all CLI args to the plugin. This way they the plugins can add their own `--help` strings to document the argument, argparse will raise if two plugins use the same name, etc.

I think we'd need another function to the plugin interface, something like
```python
def add_options(parser: argparse.ArgumentParser) -> None:
    ...
```
which is where a plugin would add its options.

Then in `mdformat._cli.run` we could pass a mapping of the parsed args to the formatter function `mdformat.text` to make the options usable from Python API as well as the CLI:
```python
import mdformat
options = vars(parser.parse_args(cli_args))
mdformat.text("bla bla", options=options)
```

2020-09-27 02:18 UTC, hukkinj1 commented
We could make defining `add_options` optional for the plugin by getting the function from the plugin with `getattr` and some default.

What do you think?

2020-09-27 02:35 UTC, chrisjsewell commented
> What do you think?

Yeh absolutely, I thought you'd be more willing to accept a simpler approach lol, but that is more of a "complete" solution 👍

2020-09-27 02:54 UTC, chrisjsewell commented
> Then in the render phase we'd pass all CLI args to the plugin

I think these options should still be stored in `mdit.options` though, potentially under a top-level key, e.g.

```python
mdit = MarkdownIt()
options = vars(parser.parse_args(cli_args))
mdit.options["mdformat"] = options
```

2020-09-27 03:07 UTC, chrisjsewell commented
> We could make defining add_options optional for the plugin by getting the function from the plugin with getattr and some default.

Yeh thts what I have done in #36, for allowing plugins to specify certain HTML classes to ignore when comparing the input/output HTML

2020-09-27 03:18 UTC, hukkinj1 commented
> potentially under a top-level key

I would use a top-level key too. Not sure, but perhaps even two keys, if we want to fit the current "codeformatters" and "parser_extensions" in the same top-level key. Something like:

```python
options["mdformat"]["opts"]
options["mdformat"]["codeformatters"]
options["mdformat"]["parser_extensions"]
```

2020-09-28 16:10 UTC, hukkinj1 requested changes

2020-09-28 16:10 UTC, hukkinj1 commented on mdformat/_cli.py
> +        parser.error(f'File "{e.path}" does not exist.\n')
Not sure but I would guess the newline at the end here is not needed now? (I.e. `parser.error` would act more like a `print()` than a `write()`)

2020-09-28 16:10 UTC, hukkinj1 commented on mdformat/_cli.py
> +    options = dict(args._get_kwargs())
Could we use `vars(args)` here? I wouldn't want to use private API.

2020-09-28 16:10 UTC, hukkinj1 commented on mdformat/_cli.py
> +    options.pop("paths")
I suggest we remove this and just pass all args to the plugins. The logic is simpler that way.

2020-09-28 16:10 UTC, hukkinj1 commented on mdformat/plugins.py
> +        mdit.options["mdformat"]"""
Maybe a mention that defining this function is optional?

2020-09-28 16:10 UTC, hukkinj1 commented on mdformat/plugins.py
> +        pass
The `pass` should be redundant here, since the docstring is a Python statement. (In fact same applies to all method implementations in this class)

2020-09-29 22:44 UTC, chrisjsewell commented on mdformat/_api.py
> +    markdown_it.options["mdformat"] = options
```suggestion
    markdown_it.options["mdformat"] = options or {}
```

2020-09-29 22:45 UTC, chrisjsewell commented on mdformat/_api.py
>      markdown_it = MarkdownIt(renderer_cls=MDRenderer)
done below

2020-09-29 22:45 UTC, chrisjsewell commented on mdformat/_cli.py
> +        parser.error(f'File "{e.path}" does not exist.\n')
```suggestion
        parser.error(f'File "{e.path}" does not exist.')
```

2020-09-29 22:45 UTC, chrisjsewell commented on mdformat/_cli.py
> +    options = dict(args._get_kwargs())
```suggestion
    options = vars(args)
```

2020-09-29 22:46 UTC, chrisjsewell commented on mdformat/plugins.py
> +        mdit.options["mdformat"]"""
```suggestion
        mdit.options["mdformat"] (optional)"""
```

2020-09-29 22:47 UTC, chrisjsewell commented on mdformat/plugins.py
> +        pass
```suggestion
```

2020-09-29 22:47 UTC, chrisjsewell commented on mdformat/plugins.py
>          pass
```suggestion
```

2020-09-29 23:32 UTC, hukkinj1 commented
Looking very good! There's one unresolved comment I think you might have missed.

2020-09-30 03:40 UTC, chrisjsewell commented
yeh I just had to fix the test

2020-09-30 11:59 UTC, merged

2020-09-30 12:00 UTC, hukkinj1 commented
Beautiful, thanks! Merged